# ============================================================
# Resources | cert-clusterissuer
# ============================================================

resources:
  - spc-cloudflare.yaml
  - ci-letsencrypt-dns01.yaml
