# ============================================================
# Patch - WordPress External Database (Development)
# ============================================================

externalDatabase:
  database: wordpress_dev
