  # ------------------------------------------------------------
  # Vault Monitoring | Prometheus Token & Client Certificate
  # ------------------------------------------------------------
  resources:
  - sa-vault.yaml
  - spc-vault-prometheus-token.yaml
  - job-vault-prometheus-token.yaml
  - cert-vault-metrics-client.yaml