# ============================================================
# IngressRoute â€” Traefik Dashboard (via Traefik)
# ============================================================

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik

spec:
  # ------------------------------------------------------------
  # EntryPoints
  # ------------------------------------------------------------
  entryPoints:
    - websecure

  # ------------------------------------------------------------
  # Routes
  # ------------------------------------------------------------
  routes:
    - match: Host(`traefik.kub.techcats.org`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService

  # ------------------------------------------------------------
  # TLS Configuration
  # ------------------------------------------------------------
  tls:
    secretName: traefik-tls-secret
