# ============================================================
# Kustomization â€” phpMyAdmin (Ingress + TLS)
# TechCats Homelab
# ============================================================

resources:
  # ------------------------------------------------------------
  # IngressRoute (Traefik)
  # ------------------------------------------------------------
  - ir-phpmyadmin.yaml

  # ------------------------------------------------------------
  # TLS Certificate (cert-manager)
  # ------------------------------------------------------------
  - cert-phpmyadmin.yaml
